* Понятие внедрения

SDLC - жизненный цикл разработки ПО

Software Development Life Cycle

** Этапы SDLC при разработке IT-продукта

=Dev Ops= - тот человек в компании, который настраивает информационную среду,
чтобы было удобно тестировать продукт на разных системах. 
Он разворачивает всю инфраструктуру для внедрения заказчику.
Создает сервера, занимается конфигурированием, устанавливает виртуальные машины.

=Внедрение ПО= - (implementation) процесс настройки ПО по определенные условия использования, 
а также обучения пользователей работе с программным продуктом.

Любая компьютерная система — средство для управления и достижения целей предприятия. 
Любое предприятие является уникальным и, в силу своей уникальности, 
требует уникального подхода к построению методик управления

** Основные работы этапа внедрения 
1. Выделение критических, с точки зрения общего 
   результата, процедур в деятельности организации.
2. Расширение нормативной базы организации путем включения 
   в неё регламентов, описывающих порядок выполнения 
   процедур автоматизируемых процессов.
3. Общая стандартизация существующей деятельности организации, 
   выделение лучших практик выполнения процедур по принципу наибольшей 
   полезности для большинства участников.

*** Внедрение ПО состоялось?

Только в том случае, если…
- [X] Продукт выполняет поставленную задачу полностью
- [X] Сотрудники компании полностью перешли на работу с новым продуктом

** Цели и задачи внедрения

1. Обеспечение стабильной повторяемости 
   результатов с заданным качеством
2. Снижение квалификационнных требований к участникам процесса.
3. Сокращение сроков выполнения проектов

** Основные действующие лица проекта внедрения

1. Менеджер-руководитель проекта (Project Manager)
2. Спонсор-куратор проекта (Project Sponsor)
3. Заказчик-потребитель проекта (Project Customer)
4. Пользователь
5. Аналитик-разработчик системы
6. Руководитель функционального подразделения
7. Функциональный лидер проекта
8. Консультант по внедрению


** Обязанности консультанта по внедрению

1. Обучение членов рабочей группы методологии внедрения, применяемой в данном проекте.

2. Ответственность за соблюдением сроков внедрения конкретных модулей программного продукта

3. Разработка необходимой документации

4. Помощь в процессе настройки ПП на сформулированные требования

5. Разработка методики испытаний и управление рабочей группой во время проведения испытаний

6. Мониторинг результатов внедрения и внесение необходимых модификаций

7. Обсуждение замечаний пользователей и выявленных узких мест проекта

8. Обучение пользователей работе с программным продуктом

9. Подготовка учебных материалов

10. Консультации пользователей при работе с ПП.


** Этапы внедрения

*** TODO

** Источники проблем

*** TODO
